# Generated by Django 6.0.7 on 2026-10-09 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('especialidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PublicacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_publicacao', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('midia', models.FileField(blank=True, null=True, upload_to='midias/')),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='gerencia.publicadormodel')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaComentarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_avaliacao', models.IntegerField()),
                ('resposta_comentario', models.TextField(blank=True, max_length=500, null=True)),
                ('data_resposta', models.DateField(auto_now=True)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_comentarios', to='gerencia.publicacaomodel')),
            ],
        ),
    ]
